[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"
description = "Rustで実装されたライフゲーム"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
rand = "0.8.5"
strum = { version = "0.26.3", features = ["derive"] }
